### ISSUE TITLE
Couldn't connect to the device

### ISSUE THREAD

**Issue by richxcame** [LMJayasundara/cashcode_npm#1]
Hi @LMJayasundara  I have issues with connecting to the device. I have MSM 3005. Here are shown errors when running ```node package/test.js```

```
Device error: Device not powerup
```
I also tried it with auto detect port + defining a port. Please, can you help me?

**Comment by LMJayasundara** [comment]
Its says serial port is already open.
The problem is device not communicate with program. There are tow reason
for that.
    1. Usb cable is not working
    2. Your device use deferent hex code to commands (like poll, reset, get
device info etc.)

**Comment by richxcame** [comment]
Thank you for your response, I think second is my issue.
What can I do?

**Comment by richxcame** [comment]
Sorry, I didn't understand what you mean. I checked hex codes before I try, they are all same!
I also think that USB is working too

**Comment by richxcame** [comment]
How can I check problem from USB or not?

**Comment by LMJayasundara** [comment]
Is there any documentation about your device

**Comment by richxcame** [comment]
CashCode MSM3005. I thought problem is coming from Windows' drivers. We switched ATM's OS from Windows 10 to Ubuntu and changed device (port) name from `COM3` to `/dev/ttyS0`. Finally it worked!

Thank you for your response and for your library ❤️.
