### ISSUE TITLE
`device.connect()` automatically calls poll

### ISSUE THREAD

**Issue by richxcame** [LMJayasundara/cashcode_npm#2]
When I call `device.connect()` package automatically starts `poll`, so its means that every time if I want to accept bill I need to create connection and that's why I can handle `cassetteRemoved`, `cassetteFull`,... events every time in connection.

It would be better if we create connections once and listening events there. And if I want to accept bills, calling start can be helpful.

How do think? Is it against for cashcode logic?

**Comment by richxcame** [comment]
TL;DR

Do I need to execute `device.connect()` every time when I call controller (for example)

**Comment by richxcame** [comment]
ping @LMJayasundara

Please @LMJayasundara help me about this.

**Comment by richxcame** [comment]
Its just a question about how to use this package...

**Comment by richxcame** [comment]
I was in hurry so forked your repo and created [cashcodejs](http://npmjs.com/cashcodejs) for my own needs

**Comment by LMJayasundara** [comment]
No problem bro. I was busy. Take it your control ❤
